from langgraph.graph import  MessagesState 
from typing import Literal
from pydantic import BaseModel, Field

class ManagerOutput(BaseModel):
    decision: Literal["chats", "code_gen", "summarizer"] = Field( description="Classification of user query: chats for conversation, code_gen for new analysis, summarizer for follow-up questions")
    messages: str | None = Field( description="Direct response message for chitchat. Only populate when decision is 'chats'")
    question: str | None = Field( description="Extracted question for code_gen or summarizer. Clear, actionable task description")

class GeneratorOutput(BaseModel):
    thinking: str = Field(description="Thinking process to solve the problem in bullet points")
    code: str = Field(description="Code to solve the problem")
    charts_exists: bool = Field(description="Whether the code generates charts or not")
    generated_chart_names: list[str] = Field(description="List of chart names generated by the code")

class ReflectorOutput(BaseModel):
    fix_type : Literal["ENVIRONMENT_FIX", "CODE_FIX"] = Field(description="Type of fix required if its something that requires terminal cmd to run or just code_fix")
    code: str = Field(description="Correct code to resolve the error if its CODE_FIX")
    cmd: str | None = Field(description="Cmd required to resolve the error if its ENVIRNMENT_FIX")
    comment: str | None = Field(description="single line comment to explain the fix")


class AgentState(MessagesState):
    thinking: str | None
    fix_type: Literal["ENVIRONMENT_FIX", "CODE_FIX"] | None
    question: str | None
    code: str | None
    cmd: str| None
    answer: str| None 
    file_path: str | None 
    attempts: int 
    agent_error: str | None
    system_error: str | None
    reflection: ReflectorOutput | None
    charts_exists: bool | None
    generated_chart_names: list[str] | list

